# eureka多实例配置
spring:
  application:
    name: eureka-ha #定义下面三个文件的应用名称叫eureka-ha
---
spring:
  profiles: eureka1 #这里指定这个配置文件叫eureka1 相当于在resource下的 application-eureka1.yml的配置文件
  security:
    user:
      name: admin  # 安全配置 访问eureka页面是需要登录
      password: 123123
server:
  port: 8761
eureka:
  server: # eureka服务端
    enable-self-preservation: true #开启自我保护 默认是true 开启
    eviction-interval-timer-in-ms: 30000 # 配置eureka 清理没有续约的instance间隔（单位毫秒，默认是60*1000）
  instance: # eureka服务端实例配置
    hostname: eureka1 # 这里的hostname需要配置到hosts文件中指定IP 如: 127.0.0.1 eureka1
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client: # eureka客户端实例配置
    healthcheck:
      enabled: true
    serviceUrl: # 注册到其他两个节点上（如果共3个节点，那么注册到两个节点比较好）
      defaultZone: http://admin:123123@eureka2:8762/eureka/,http://admin:123123@eureka3:8763/eureka/
    fetch-registry: true # 是否从eureka服务器获取注册信息 这里需要设置为true 如果是单节点则不需要
    register-with-eureka: true # 是否注册自身到eureka服务器 这里需要设置为true 如果是单节点则不需要
---
spring:
  profiles: eureka2
  security:
    user:
      name: admin
      password: 123123
server:
  port: 8762
eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: eureka2
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://admin:123123@eureka1:8761/eureka/,http://admin:123123@eureka3:8763/eureka/
    fetch-registry: true
    register-with-eureka: true
---
server:
  port: 8763
spring:
  profiles: eureka3
  security:
    user:
      name: admin
      password: 123123
eureka:
  server:
    enable-self-preservation: true
  instance:
    hostname: eureka3
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://admin:123123@eureka1:8761/eureka/,http://admin:123123@eureka2:8762/eureka/
    fetch-registry: true
    register-with-eureka: true  